/*
 * Vault Ethereum Plugin
 *
 * This is a Vault plugin that allows for the creation of Ethereum accounts and signing of
 * transactions using those accounts. Contact Support:  Name: @kevlarxyz  Email:
 * support@kevlar.xyz
 *
 * The version of the kevlar document: 1.0
 *
 * Generated by: https://kevlar-generator.tech
 */

#[derive(Clone, Debug, PartialEq, Default, serde::Serialize, serde::Deserialize)]
pub struct Createanaccountrequest {
    pub inclusions: Option<serde_json::Value>,

    pub exclusions: Option<serde_json::Value>,
}

impl Createanaccountrequest {
    pub fn new(
        inclusions: Option<serde_json::Value>,
        exclusions: Option<serde_json::Value>,
    ) -> Createanaccountrequest {
        Createanaccountrequest { inclusions, exclusions }
    }
}
