/*
 * Vault Ethereum Plugin
 *
 * This is a Vault plugin that allows for the creation of Ethereum accounts and signing of
 * transactions using those accounts. Contact Support:  Name: @kevlarxyz  Email:
 * support@kevlar.xyz
 *
 * The version of the kevlar document: 1.0
 *
 * Generated by: https://kevlar-generator.tech
 */

#[derive(Clone, Debug, PartialEq, Default, serde::Serialize, serde::Deserialize)]
pub struct Signatransactionrequest {
    pub amount: Option<serde_json::Value>,

    pub data: Option<serde_json::Value>,

    pub to: Option<serde_json::Value>,
}

impl Signatransactionrequest {
    pub fn new(
        amount: Option<serde_json::Value>,
        data: Option<serde_json::Value>,
        to: Option<serde_json::Value>,
    ) -> Signatransactionrequest {
        Signatransactionrequest { amount, data, to }
    }
}
