/*
 * Vault Ethereum Plugin
 *
 * This is a Vault plugin that allows for the creation of Ethereum accounts and signing of
 * transactions using those accounts. Contact Support:  Name: @kevlarxyz  Email:
 * support@kevlar.xyz
 *
 * The version of the kevlar document: 1.0
 *
 * Generated by: https://kevlar-generator.tech
 */

#[derive(Clone, Debug, PartialEq, Default, serde::Serialize, serde::Deserialize)]
pub struct Signamessagerequest {
    pub message: Option<serde_json::Value>,
}

impl Signamessagerequest {
    pub fn new(message: Option<serde_json::Value>) -> Signamessagerequest {
        Signamessagerequest { message }
    }
}
