/*
 * Vault Ethereum Plugin
 *
 * This is a Vault plugin that allows for the creation of Ethereum accounts and signing of
 * transactions using those accounts. Contact Support:  Name: @kevlarxyz  Email:
 * support@kevlar.xyz
 *
 * The version of the kevlar document: 1.0
 *
 * Generated by: https://kevlar-generator.tech
 */

#[derive(Clone, Debug, PartialEq, Default, serde::Serialize, serde::Deserialize)]
pub struct Writeaconfigurationrequest {
    // #[serde(rename = "chain_id", deserialize_with = "Option::deserialize")]
    pub chain_id: Option<serde_json::Value>,
    // #[serde(rename = "rpc_url", deserialize_with = "Option::deserialize")]
    pub rpc_url: Option<serde_json::Value>,
}

impl Writeaconfigurationrequest {
    pub fn new(
        chain_id: Option<serde_json::Value>,
        rpc_url: Option<serde_json::Value>,
    ) -> Writeaconfigurationrequest {
        Writeaconfigurationrequest { chain_id, rpc_url }
    }
}
